<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class FakeProfileSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = $this->getProfiles();

        foreach ($profiles as $p) {
            $dob = Carbon::now()->subYears($p['age'])->subDays(rand(0, 365));

            $user = DB::table('users')->insertGetId([
                'name'              => $p['name'],
                'email'             => $p['email'],
                'password'          => Hash::make('FakeDemo2025!'),
                'provider'          => 'email',
                'is_fake'           => 1,
                'status'            => 1,
                'is_vip'            => false,
                'email_verified_at' => now(),
                'last_activity'     => now()->subMinutes(rand(1, 120)),
                'created_at'        => now()->subDays(rand(1, 30)),
                'updated_at'        => now(),
            ]);

            DB::table('user_information')->insert([
                'user_id'            => $user,
                'bio'                => $p['bio'],
                'gender'             => $p['gender'],
                'date_of_birth'      => $dob->toDateString(),
                'age'                => $p['age'],
                'search_preference'  => $p['gender'] === 'male' ? 'female' : 'male',
                'latitude'           => $p['lat'],
                'longitude'          => $p['lng'],
                'country_code'       => $p['country_code'],
                'religion_id'        => $p['religion_id'],
                'education_id'       => $p['education_id'],
                'carrer_field_id'    => $p['career_id'],
                'ethnicity_id'       => $p['ethnicity_id'],
                'relationship_status_id' => 7,
                'height'             => $p['height'],
                'interests'          => json_encode($p['interests']),
                'languages'          => json_encode($p['languages']),
                'relation_goals'     => json_encode($p['goals']),
                'search_radius'      => 100.0,
                'visible_on_map'     => true,
                'alkohol'            => $p['alcohol'] ?? 'prefer_not_to_say',
                'smoke'              => $p['smoke'] ?? 'prefer_not_to_say',
                'images'             => json_encode([]),
                'created_at'         => now(),
                'updated_at'         => now(),
            ]);
        }

        $this->command->info('Created ' . count($profiles) . ' fake demo profiles.');
    }

    private function getProfiles(): array
    {
        return [
            // ─── NIGERIA (10) ───────────────────────────────────────
            [
                'name' => 'Amina Bello', 'email' => 'demo.amina@inmessage.test',
                'gender' => 'female', 'age' => 24, 'height' => 165,
                'lat' => 6.5244, 'lng' => 3.3792, 'country_code' => '+234',
                'bio' => 'Medical student who loves afrobeats and jollof rice debates. Looking for someone who can keep up with my energy.',
                'religion_id' => 1, 'education_id' => 9, 'career_id' => 4, 'ethnicity_id' => 10,
                'interests' => [11, 2, 1], 'languages' => [14, 4], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Chidi Okafor', 'email' => 'demo.chidi@inmessage.test',
                'gender' => 'male', 'age' => 27, 'height' => 180,
                'lat' => 6.4541, 'lng' => 3.3947, 'country_code' => '+234',
                'bio' => 'Software engineer by day, football fanatic by night. Arsenal through and through.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 8, 'ethnicity_id' => 10,
                'interests' => [5, 10, 16], 'languages' => [14], 'goals' => [1],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Fatima Yusuf', 'email' => 'demo.fatima@inmessage.test',
                'gender' => 'female', 'age' => 22, 'height' => 160,
                'lat' => 9.0579, 'lng' => 7.4951, 'country_code' => '+234',
                'bio' => 'Fashion design student in Abuja. I sketch more than I text but I promise I reply.',
                'religion_id' => 1, 'education_id' => 5, 'career_id' => 7, 'ethnicity_id' => 10,
                'interests' => [22, 20, 14], 'languages' => [14, 4], 'goals' => [2],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Emeka Nwosu', 'email' => 'demo.emeka@inmessage.test',
                'gender' => 'male', 'age' => 30, 'height' => 178,
                'lat' => 6.5059, 'lng' => 3.3731, 'country_code' => '+234',
                'bio' => 'Entrepreneur running a logistics startup. Big on travel and trying new restaurants.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 9, 'ethnicity_id' => 10,
                'interests' => [1, 2, 19], 'languages' => [14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Ngozi Adeyemi', 'email' => 'demo.ngozi@inmessage.test',
                'gender' => 'female', 'age' => 26, 'height' => 168,
                'lat' => 6.6018, 'lng' => 3.3515, 'country_code' => '+234',
                'bio' => 'Lawyer in training. I love good conversations, art exhibitions, and weekend road trips.',
                'religion_id' => 2, 'education_id' => 7, 'career_id' => 15, 'ethnicity_id' => 10,
                'interests' => [7, 21, 1], 'languages' => [14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Tunde Bakare', 'email' => 'demo.tunde@inmessage.test',
                'gender' => 'male', 'age' => 25, 'height' => 175,
                'lat' => 7.3776, 'lng' => 3.9470, 'country_code' => '+234',
                'bio' => 'Content creator from Ibadan. If you can make me laugh, you have my attention.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 11, 'ethnicity_id' => 10,
                'interests' => [13, 16, 6], 'languages' => [14], 'goals' => [4],
                'alcohol' => 'drink_socially', 'smoke' => 'prefer_not_to_say',
            ],
            [
                'name' => 'Halima Abdullahi', 'email' => 'demo.halima@inmessage.test',
                'gender' => 'female', 'age' => 23, 'height' => 162,
                'lat' => 12.0022, 'lng' => 8.5920, 'country_code' => '+234',
                'bio' => 'Pharmacist in Kano. Bookworm with a soft spot for cats and Bollywood movies.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 4, 'ethnicity_id' => 10,
                'interests' => [7, 8, 6], 'languages' => [14, 4], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Oluwatobi Eze', 'email' => 'demo.tobi@inmessage.test',
                'gender' => 'male', 'age' => 28, 'height' => 183,
                'lat' => 6.4281, 'lng' => 3.4219, 'country_code' => '+234',
                'bio' => 'Gym bro who also knows his way around the kitchen. Let me cook for you sometime.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 3, 'ethnicity_id' => 10,
                'interests' => [10, 2, 19], 'languages' => [14], 'goals' => [1],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Blessing Okoro', 'email' => 'demo.blessing@inmessage.test',
                'gender' => 'female', 'age' => 25, 'height' => 170,
                'lat' => 6.3350, 'lng' => 5.6037, 'country_code' => '+234',
                'bio' => 'Nurse in Benin City. Dancing is my therapy and plantain is my love language.',
                'religion_id' => 2, 'education_id' => 4, 'career_id' => 4, 'ethnicity_id' => 10,
                'interests' => [11, 2, 22], 'languages' => [14], 'goals' => [5],
                'alcohol' => 'prefer_not_to_say', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Yusuf Ibrahim', 'email' => 'demo.yusuf@inmessage.test',
                'gender' => 'male', 'age' => 29, 'height' => 176,
                'lat' => 9.0600, 'lng' => 7.4900, 'country_code' => '+234',
                'bio' => 'Civil engineer based in Abuja. Weekend hiker, weekday hustler.',
                'religion_id' => 1, 'education_id' => 7, 'career_id' => 3, 'ethnicity_id' => 10,
                'interests' => [9, 14, 1], 'languages' => [14, 4], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],

            // ─── USA (10) ────────────────────────────────────────────
            [
                'name' => 'Maya Johnson', 'email' => 'demo.maya@inmessage.test',
                'gender' => 'female', 'age' => 26, 'height' => 168,
                'lat' => 40.7128, 'lng' => -74.0060, 'country_code' => '+1',
                'bio' => 'Marketing manager in NYC. Brunch enthusiast and aspiring marathon runner.',
                'religion_id' => 6, 'education_id' => 8, 'career_id' => 6, 'ethnicity_id' => 6,
                'interests' => [1, 2, 14], 'languages' => [1], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'James Carter', 'email' => 'demo.james@inmessage.test',
                'gender' => 'male', 'age' => 28, 'height' => 185,
                'lat' => 34.0522, 'lng' => -118.2437, 'country_code' => '+1',
                'bio' => 'Film editor in LA. Obsessed with indie movies and hiking trails at sunset.',
                'religion_id' => 6, 'education_id' => 8, 'career_id' => 11, 'ethnicity_id' => 6,
                'interests' => [6, 9, 14], 'languages' => [1], 'goals' => [1],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Priya Patel', 'email' => 'demo.priya@inmessage.test',
                'gender' => 'female', 'age' => 24, 'height' => 160,
                'lat' => 37.7749, 'lng' => -122.4194, 'country_code' => '+1',
                'bio' => 'Data scientist in San Francisco. Yoga mornings, coding afternoons, Netflix nights.',
                'religion_id' => 3, 'education_id' => 7, 'career_id' => 8, 'ethnicity_id' => 9,
                'interests' => [4, 7, 17], 'languages' => [1, 7], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'David Kim', 'email' => 'demo.david@inmessage.test',
                'gender' => 'male', 'age' => 31, 'height' => 177,
                'lat' => 41.8781, 'lng' => -87.6298, 'country_code' => '+1',
                'bio' => 'Architect in Chicago. I design buildings for a living and playlists for fun.',
                'religion_id' => 6, 'education_id' => 7, 'career_id' => 7, 'ethnicity_id' => 9,
                'interests' => [11, 20, 9], 'languages' => [1, 9], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Ashley Thomas', 'email' => 'demo.ashley@inmessage.test',
                'gender' => 'female', 'age' => 27, 'height' => 172,
                'lat' => 29.7604, 'lng' => -95.3698, 'country_code' => '+1',
                'bio' => 'Nurse in Houston. Country music, BBQ, and a good book on the porch.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 4, 'ethnicity_id' => 6,
                'interests' => [11, 2, 7], 'languages' => [1], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Marcus Brown', 'email' => 'demo.marcus@inmessage.test',
                'gender' => 'male', 'age' => 26, 'height' => 188,
                'lat' => 33.7490, 'lng' => -84.3880, 'country_code' => '+1',
                'bio' => 'Personal trainer in Atlanta. If you can beat me at basketball, dinner is on me.',
                'religion_id' => 2, 'education_id' => 4, 'career_id' => 13, 'ethnicity_id' => 6,
                'interests' => [10, 19, 5], 'languages' => [1], 'goals' => [1],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Sofia Rodriguez', 'email' => 'demo.sofia@inmessage.test',
                'gender' => 'female', 'age' => 25, 'height' => 163,
                'lat' => 25.7617, 'lng' => -80.1918, 'country_code' => '+1',
                'bio' => 'Graphic designer in Miami. Bilingual, salsa dancer, sunset chaser.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 7, 'ethnicity_id' => 6,
                'interests' => [20, 14, 1], 'languages' => [1, 5], 'goals' => [5],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Ethan Miller', 'email' => 'demo.ethan@inmessage.test',
                'gender' => 'male', 'age' => 29, 'height' => 182,
                'lat' => 47.6062, 'lng' => -122.3321, 'country_code' => '+1',
                'bio' => 'Full-stack developer in Seattle. Coffee snob, board game collector, dog dad.',
                'religion_id' => 6, 'education_id' => 8, 'career_id' => 8, 'ethnicity_id' => 6,
                'interests' => [5, 18, 8], 'languages' => [1], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Aaliyah Washington', 'email' => 'demo.aaliyah@inmessage.test',
                'gender' => 'female', 'age' => 23, 'height' => 167,
                'lat' => 40.7580, 'lng' => -73.9855, 'country_code' => '+1',
                'bio' => 'Dance student at NYU. Life is too short for bad vibes and bad pizza.',
                'religion_id' => 6, 'education_id' => 5, 'career_id' => 15, 'ethnicity_id' => 6,
                'interests' => [11, 6, 13], 'languages' => [1], 'goals' => [6],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Ryan Chen', 'email' => 'demo.ryan@inmessage.test',
                'gender' => 'male', 'age' => 27, 'height' => 175,
                'lat' => 37.3382, 'lng' => -121.8863, 'country_code' => '+1',
                'bio' => 'Product manager at a tech startup. Weekend warrior who loves cycling and ramen.',
                'religion_id' => 6, 'education_id' => 7, 'career_id' => 8, 'ethnicity_id' => 9,
                'interests' => [19, 2, 5], 'languages' => [1], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],

            // ─── UK (8) ──────────────────────────────────────────────
            [
                'name' => 'Emma Clarke', 'email' => 'demo.emma@inmessage.test',
                'gender' => 'female', 'age' => 26, 'height' => 166,
                'lat' => 51.5074, 'lng' => -0.1278, 'country_code' => '+44',
                'bio' => 'Publishing assistant in London. Tea over coffee, always. Looking for someone to explore bookshops with.',
                'religion_id' => 6, 'education_id' => 7, 'career_id' => 13, 'ethnicity_id' => 8,
                'interests' => [7, 1, 21], 'languages' => [8], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Oliver Wright', 'email' => 'demo.oliver@inmessage.test',
                'gender' => 'male', 'age' => 29, 'height' => 181,
                'lat' => 53.4808, 'lng' => -2.2426, 'country_code' => '+44',
                'bio' => 'Physiotherapist in Manchester. United fan, pub quiz champion, amateur chef.',
                'religion_id' => 6, 'education_id' => 7, 'career_id' => 4, 'ethnicity_id' => 8,
                'interests' => [2, 10, 11], 'languages' => [8], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Zara Ahmed', 'email' => 'demo.zara@inmessage.test',
                'gender' => 'female', 'age' => 24, 'height' => 162,
                'lat' => 52.4862, 'lng' => -1.8904, 'country_code' => '+44',
                'bio' => 'Dentistry student in Birmingham. Foodie who documents everything on Instagram.',
                'religion_id' => 1, 'education_id' => 5, 'career_id' => 15, 'ethnicity_id' => 9,
                'interests' => [2, 14, 22], 'languages' => [8, 4], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Liam Murphy', 'email' => 'demo.liam@inmessage.test',
                'gender' => 'male', 'age' => 27, 'height' => 178,
                'lat' => 51.4545, 'lng' => -2.5879, 'country_code' => '+44',
                'bio' => 'Music producer in Bristol. If you like drum and bass, we already have something in common.',
                'religion_id' => 6, 'education_id' => 8, 'career_id' => 13, 'ethnicity_id' => 8,
                'interests' => [11, 5, 16], 'languages' => [8], 'goals' => [5],
                'alcohol' => 'drink_socially', 'smoke' => 'prefer_not_to_say',
            ],
            [
                'name' => 'Chloe Williams', 'email' => 'demo.chloe@inmessage.test',
                'gender' => 'female', 'age' => 28, 'height' => 170,
                'lat' => 55.9533, 'lng' => -3.1883, 'country_code' => '+44',
                'bio' => 'Veterinarian in Edinburgh. Hiking the Highlands with my collie is my idea of a perfect weekend.',
                'religion_id' => 6, 'education_id' => 6, 'career_id' => 4, 'ethnicity_id' => 8,
                'interests' => [8, 9, 14], 'languages' => [8], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Hassan Khan', 'email' => 'demo.hassan@inmessage.test',
                'gender' => 'male', 'age' => 25, 'height' => 176,
                'lat' => 53.8008, 'lng' => -1.5491, 'country_code' => '+44',
                'bio' => 'Accounting graduate in Leeds. Cricket on weekends, biryani experiments on weekdays.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 13, 'ethnicity_id' => 9,
                'interests' => [2, 10, 7], 'languages' => [8, 4], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Isla Scott', 'email' => 'demo.isla@inmessage.test',
                'gender' => 'female', 'age' => 23, 'height' => 165,
                'lat' => 51.4816, 'lng' => -3.1791, 'country_code' => '+44',
                'bio' => 'Psychology student in Cardiff. Beach walks, true crime podcasts, and too much chocolate.',
                'religion_id' => 6, 'education_id' => 5, 'career_id' => 15, 'ethnicity_id' => 8,
                'interests' => [7, 6, 16], 'languages' => [8], 'goals' => [1],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Daniel Osei', 'email' => 'demo.daniel@inmessage.test',
                'gender' => 'male', 'age' => 30, 'height' => 184,
                'lat' => 51.5200, 'lng' => -0.0780, 'country_code' => '+44',
                'bio' => 'Financial analyst in London. Ghana roots, British raised. Love live music and street food.',
                'religion_id' => 2, 'education_id' => 7, 'career_id' => 13, 'ethnicity_id' => 10,
                'interests' => [11, 2, 1], 'languages' => [8], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],

            // ─── UAE / MIDDLE EAST (6) ───────────────────────────────
            [
                'name' => 'Layla Al-Rashid', 'email' => 'demo.layla@inmessage.test',
                'gender' => 'female', 'age' => 25, 'height' => 164,
                'lat' => 25.2048, 'lng' => 55.2708, 'country_code' => '+971',
                'bio' => 'Interior designer in Dubai. Coffee addict and sunset photographer.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 7, 'ethnicity_id' => 7,
                'interests' => [14, 22, 2], 'languages' => [4, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Omar Farouk', 'email' => 'demo.omar@inmessage.test',
                'gender' => 'male', 'age' => 28, 'height' => 179,
                'lat' => 25.1972, 'lng' => 55.2744, 'country_code' => '+971',
                'bio' => 'Real estate manager in Dubai. Gym mornings, business meetings, and weekend desert drives.',
                'religion_id' => 1, 'education_id' => 7, 'career_id' => 10, 'ethnicity_id' => 7,
                'interests' => [10, 1, 19], 'languages' => [4, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Noor Hassan', 'email' => 'demo.noor@inmessage.test',
                'gender' => 'female', 'age' => 23, 'height' => 158,
                'lat' => 24.4539, 'lng' => 54.3773, 'country_code' => '+971',
                'bio' => 'Marketing graduate in Abu Dhabi. Art galleries, iced lattes, and long conversations.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 6, 'ethnicity_id' => 7,
                'interests' => [20, 14, 7], 'languages' => [4, 14], 'goals' => [5],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Khalid Mansour', 'email' => 'demo.khalid@inmessage.test',
                'gender' => 'male', 'age' => 31, 'height' => 182,
                'lat' => 25.3463, 'lng' => 55.4209, 'country_code' => '+971',
                'bio' => 'IT consultant in Sharjah. Tech nerd who also happens to love cooking traditional food.',
                'religion_id' => 1, 'education_id' => 7, 'career_id' => 8, 'ethnicity_id' => 7,
                'interests' => [2, 5, 17], 'languages' => [4, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Sara Mahmoud', 'email' => 'demo.sara@inmessage.test',
                'gender' => 'female', 'age' => 26, 'height' => 166,
                'lat' => 25.2854, 'lng' => 51.5310, 'country_code' => '+974',
                'bio' => 'Architect in Doha. I design spaces and dream about traveling the world.',
                'religion_id' => 1, 'education_id' => 7, 'career_id' => 7, 'ethnicity_id' => 7,
                'interests' => [1, 20, 14], 'languages' => [4, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Ahmed Nasser', 'email' => 'demo.ahmed@inmessage.test',
                'gender' => 'male', 'age' => 27, 'height' => 177,
                'lat' => 21.4858, 'lng' => 39.1925, 'country_code' => '+966',
                'bio' => 'Mechanical engineer in Jeddah. Diving the Red Sea reefs is my weekend escape.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 3, 'ethnicity_id' => 7,
                'interests' => [1, 10, 14], 'languages' => [4, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],

            // ─── SOUTH ASIA (6) ─────────────────────────────────────
            [
                'name' => 'Aisha Rahman', 'email' => 'demo.aisha@inmessage.test',
                'gender' => 'female', 'age' => 24, 'height' => 160,
                'lat' => 23.8103, 'lng' => 90.4125, 'country_code' => '+880',
                'bio' => 'UX designer in Dhaka. Tea lover, cat person, and weekend painter.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 7, 'ethnicity_id' => 9,
                'interests' => [20, 8, 4], 'languages' => [3, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Arjun Mehta', 'email' => 'demo.arjun@inmessage.test',
                'gender' => 'male', 'age' => 27, 'height' => 175,
                'lat' => 19.0760, 'lng' => 72.8777, 'country_code' => '+91',
                'bio' => 'Backend developer in Mumbai. Cricket and chai are non-negotiable.',
                'religion_id' => 3, 'education_id' => 8, 'career_id' => 8, 'ethnicity_id' => 9,
                'interests' => [5, 2, 16], 'languages' => [7, 14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Tanisha Roy', 'email' => 'demo.tanisha@inmessage.test',
                'gender' => 'female', 'age' => 25, 'height' => 162,
                'lat' => 28.6139, 'lng' => 77.2090, 'country_code' => '+91',
                'bio' => 'Content writer in Delhi. Bookstores are my happy place. Swipe right if you read.',
                'religion_id' => 3, 'education_id' => 7, 'career_id' => 11, 'ethnicity_id' => 9,
                'interests' => [7, 21, 6], 'languages' => [7, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Rafiq Hossain', 'email' => 'demo.rafiq@inmessage.test',
                'gender' => 'male', 'age' => 26, 'height' => 173,
                'lat' => 22.3569, 'lng' => 91.7832, 'country_code' => '+880',
                'bio' => 'Teacher in Chittagong. Passionate about education and exploring new places on my motorcycle.',
                'religion_id' => 1, 'education_id' => 7, 'career_id' => 13, 'ethnicity_id' => 9,
                'interests' => [1, 9, 14], 'languages' => [3, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Meera Sharma', 'email' => 'demo.meera@inmessage.test',
                'gender' => 'female', 'age' => 23, 'height' => 157,
                'lat' => 12.9716, 'lng' => 77.5946, 'country_code' => '+91',
                'bio' => 'Software engineer in Bangalore. Yoga, filter coffee, and weekend treks to the Western Ghats.',
                'religion_id' => 3, 'education_id' => 8, 'career_id' => 8, 'ethnicity_id' => 9,
                'interests' => [4, 9, 19], 'languages' => [7, 14], 'goals' => [5],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Imran Ali', 'email' => 'demo.imran@inmessage.test',
                'gender' => 'male', 'age' => 29, 'height' => 180,
                'lat' => 24.8607, 'lng' => 67.0011, 'country_code' => '+92',
                'bio' => 'Doctor in Karachi. When I am not at the hospital you will find me at the cricket ground.',
                'religion_id' => 1, 'education_id' => 6, 'career_id' => 4, 'ethnicity_id' => 9,
                'interests' => [10, 1, 7], 'languages' => [4, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],

            // ─── SOUTHEAST ASIA (5) ─────────────────────────────────
            [
                'name' => 'Putri Wulandari', 'email' => 'demo.putri@inmessage.test',
                'gender' => 'female', 'age' => 24, 'height' => 158,
                'lat' => -6.2088, 'lng' => 106.8456, 'country_code' => '+62',
                'bio' => 'Marketing executive in Jakarta. Foodie who rates every restaurant she visits.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 6, 'ethnicity_id' => 9,
                'interests' => [2, 14, 22], 'languages' => [6, 14], 'goals' => [3],
                'alcohol' => 'dont_drink', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Rizky Pratama', 'email' => 'demo.rizky@inmessage.test',
                'gender' => 'male', 'age' => 27, 'height' => 172,
                'lat' => -6.1751, 'lng' => 106.8650, 'country_code' => '+62',
                'bio' => 'Freelance photographer in Jakarta. Always chasing golden hour.',
                'religion_id' => 1, 'education_id' => 8, 'career_id' => 13, 'ethnicity_id' => 9,
                'interests' => [14, 1, 9], 'languages' => [6, 14], 'goals' => [5],
                'alcohol' => 'dont_drink', 'smoke' => 'smoke_occasionally',
            ],
            [
                'name' => 'Ling Wei', 'email' => 'demo.lingwei@inmessage.test',
                'gender' => 'female', 'age' => 25, 'height' => 163,
                'lat' => 1.3521, 'lng' => 103.8198, 'country_code' => '+65',
                'bio' => 'Financial analyst in Singapore. Bubble tea connoisseur and K-drama addict.',
                'religion_id' => 4, 'education_id' => 7, 'career_id' => 13, 'ethnicity_id' => 9,
                'interests' => [6, 22, 2], 'languages' => [14, 9], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Thanat Supachai', 'email' => 'demo.thanat@inmessage.test',
                'gender' => 'male', 'age' => 28, 'height' => 174,
                'lat' => 13.7563, 'lng' => 100.5018, 'country_code' => '+66',
                'bio' => 'Game developer in Bangkok. If you love gaming and street food, we will get along.',
                'religion_id' => 4, 'education_id' => 8, 'career_id' => 8, 'ethnicity_id' => 9,
                'interests' => [5, 2, 13], 'languages' => [14], 'goals' => [4],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Maria Santos', 'email' => 'demo.maria@inmessage.test',
                'gender' => 'female', 'age' => 26, 'height' => 155,
                'lat' => 14.5995, 'lng' => 120.9842, 'country_code' => '+63',
                'bio' => 'Registered nurse in Manila. Travel planner on weekends and karaoke queen always.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 4, 'ethnicity_id' => 9,
                'interests' => [1, 11, 2], 'languages' => [14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],

            // ─── SOUTH AFRICA (5) ───────────────────────────────────
            [
                'name' => 'Thandi Nkosi', 'email' => 'demo.thandi@inmessage.test',
                'gender' => 'female', 'age' => 25, 'height' => 168,
                'lat' => -26.2041, 'lng' => 28.0473, 'country_code' => '+27',
                'bio' => 'PR specialist in Johannesburg. Wine tasting, live jazz, and good company.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 6, 'ethnicity_id' => 10,
                'interests' => [3, 11, 1], 'languages' => [14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Sipho Dlamini', 'email' => 'demo.sipho@inmessage.test',
                'gender' => 'male', 'age' => 28, 'height' => 181,
                'lat' => -33.9249, 'lng' => 18.4241, 'country_code' => '+27',
                'bio' => 'Mechanical engineer in Cape Town. Surfing, braai, and rugby Saturdays.',
                'religion_id' => 2, 'education_id' => 8, 'career_id' => 3, 'ethnicity_id' => 10,
                'interests' => [10, 2, 9], 'languages' => [14], 'goals' => [1],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Naledi Mokoena', 'email' => 'demo.naledi@inmessage.test',
                'gender' => 'female', 'age' => 27, 'height' => 165,
                'lat' => -29.8587, 'lng' => 31.0218, 'country_code' => '+27',
                'bio' => 'Teacher in Durban. Beach mornings, reading afternoons, and cooking experiments.',
                'religion_id' => 2, 'education_id' => 7, 'career_id' => 13, 'ethnicity_id' => 10,
                'interests' => [7, 2, 14], 'languages' => [14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Bongani Zulu', 'email' => 'demo.bongani@inmessage.test',
                'gender' => 'male', 'age' => 26, 'height' => 179,
                'lat' => -26.1052, 'lng' => 28.0560, 'country_code' => '+27',
                'bio' => 'Junior doctor in Joburg. When not saving lives I am binge-watching anime.',
                'religion_id' => 2, 'education_id' => 6, 'career_id' => 4, 'ethnicity_id' => 10,
                'interests' => [6, 5, 19], 'languages' => [14], 'goals' => [3],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
            [
                'name' => 'Lerato Khumalo', 'email' => 'demo.lerato@inmessage.test',
                'gender' => 'female', 'age' => 24, 'height' => 170,
                'lat' => -25.7479, 'lng' => 28.2293, 'country_code' => '+27',
                'bio' => 'Graphic designer in Pretoria. Art, coffee shops, and spontaneous adventures.',
                'religion_id' => 6, 'education_id' => 8, 'career_id' => 7, 'ethnicity_id' => 10,
                'interests' => [20, 14, 1], 'languages' => [14], 'goals' => [5],
                'alcohol' => 'drink_socially', 'smoke' => 'dont_smoke',
            ],
        ];
    }
}
